"""
'systolic blood pressure',
'diastolic blood pressure',
'oxygen saturation',
'temperature',
'glucose',
'central venous pressure',
'potassium',
'sodium',
'creatinine',
'chloride',
'blood urea nitrogen',
'hemoglobin',
"""
PI_VITALS = [
                'white blood cell count',
                'red blood cell count',
                #'magnesium',
                #'calcium',
                #'phosphorous',
                'glascow coma scale total',
                #'co2',
                #'ph',
                #'co2 (etco2, pco2, etc.)',
                'weight',
                #'central venous pressure',
                #'lactic acid',
                'ph urine',
                'cardiac index',
                'systemic vascular resistance',
                'creatinine urine',
                'red blood cell count urine',
                'white blood cell count urine',
                'cholesterol',
                'cholesterol hdl',
                'cholesterol ldl',
                #'chloride urine',
                #'total protein urine',
                #'red blood cell count csf',
                #'lymphocytes body fluid',
                #'total protein',
                #'red blood cell count ascites',
                #'red blood cell count pleural',
                #'calcium urine',
                #'creatinine body fluid',
        ]
